version: '3.8'

services:
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop
    restart: always
    depends_on:
      - broker-1
      - broker-2
      - broker-3
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "broker-1:19092,broker-2:19092,broker-3:19092"
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_PORT: 9000
